# Generated by update.sh — do not edit manually.
# Edit modules.conf and run this script again.

FROM caddy:2.11.2-builder-alpine AS builder

RUN --mount=type=cache,target=/go/pkg/mod \
--mount=type=cache,target=/root/.cache/go-build \
xcaddy build \
--with github.com/lucaslorentz/caddy-docker-proxy/v2@v2.12.0 \
--with github.com/greenpau/caddy-security@v1.1.62 \
--with github.com/caddy-dns/cloudflare@v0.2.4 \
--with github.com/mholt/caddy-l4@v0.1.0

FROM caddy:2.11.2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
