# This file will be generated by the update script on updates.
# It is used to build the Caddy image with the specified modules.
# The build consists of two stages, builder first and final second.
# Don't edit this file, as it's used to calculate changed modules.
