# Here you should list the modules to include in the Caddy build.
# Each line should be specified as a Go modules path with version.
# Caddy itself must be included in that list, better if first one.
# Also, at least one module must be included for the build to work.
