# Caddy standard server
github.com/caddyserver/caddy/v2@v0.0.0

# Reverse proxy for Docker containers
github.com/lucaslorentz/caddy-docker-proxy/v2@v0.0.0

# Security module for authn and authz
github.com/greenpau/caddy-security@v0.0.0

# DNS provider for Cloudflare
github.com/caddy-dns/cloudflare@v0.0.0

# Proxy for TCP and UDP
github.com/mholt/caddy-l4@v0.0.0
