# Caddy standard server
github.com/caddyserver/caddy/v2@v2.11.2

# Reverse proxy for Docker containers
github.com/lucaslorentz/caddy-docker-proxy/v2@v2.12.0

# Security module for authn and authz
github.com/greenpau/caddy-security@v1.1.62

# DNS provider for Cloudflare
github.com/caddy-dns/cloudflare@v0.2.4

# Proxy for TCP and UDP
github.com/mholt/caddy-l4@v0.1.0
