#!/bin/bash
# shellcheck enable=all

set -euo pipefail

for BIN in cat curl sed; do
	if ! hash "${BIN}" 2>/dev/null; then
		echo "ERROR: ${BIN} is not installed" >&2
		exit 1
	fi
done

MODULES_CONF="modules.conf"
DOCKERFILE="Dockerfile"
CHANGELOG="CHANGELOG.md"
GOPROXY="https://proxy.golang.org"
CADDY_MODULE="github.com/caddyserver/caddy/v2"

DRY_RUN=
FORCE_RUN=
while [[ "$#" -gt 0 ]]; do
	case "$1" in
	-n | --dry-run)
		DRY_RUN=true
		shift
		;;
	-f | --force)
		FORCE_RUN=true
		shift
		;;
	*)
		echo "Usage: $0 [-n|--dry-run]" >&2
		exit 1
		;;
	esac
done

declare -A config=()
declare -a sorted=()
while IFS= read -r line; do
	[[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]] && continue
	module="${line%%@*}"
	config["${module}"]="${line##*@}"
	sorted+=("${module}")
done <"${MODULES_CONF}"

declare -A docker=()
while IFS= read -r line; do
	if [[ "${line}" =~ ^FROM\ caddy:(.+)-builder-alpine ]]; then
		docker["${CADDY_MODULE}"]="v${BASH_REMATCH[1]}"
	elif [[ "${line}" =~ ^[[:space:]]*--with\ (.+)$ ]]; then
		entry="${BASH_REMATCH[1]% \\}"
		docker["${entry%%@*}"]="${entry##*@}"
	fi
done <"${DOCKERFILE}"

declare -A latest=()
declare -a added=()
declare -a changed=()
declare -a removed=()
for module in "${sorted[@]}"; do
	# shellcheck disable=SC2001
	encoded=$(echo "${module}" | sed 's/[A-Z]/!\l&/g')
	response=$(curl -fsSL -m 15 "${GOPROXY}/${encoded}/@latest")
	version=$(echo "${response}" | sed -n 's/.*"Version":"\([^"]*\)".*/\1/p')
	if [[ -z "${version}" ]]; then
		echo "ERROR: Failed to get latest version for ${module}" >&2
		exit 1
	fi
	if [[ -z "${docker[${module}]+_}" ]]; then
		added+=("${module}")
		latest["${module}"]="${version}"
	elif [[ "${version}" != "${config[${module}]}" ]]; then
		changed+=("${module}")
		latest["${module}"]="${version}"
	fi
done
for module in "${!docker[@]}"; do
	[[ -z "${config[${module}]+_}" ]] && removed+=("${module}")
done

caddy="${latest[${CADDY_MODULE}]:-${config[${CADDY_MODULE}]}}"
caddy="${caddy#v}"

revision=
if [[ -n "${latest[${CADDY_MODULE}]+_}" ]]; then
	revision="0"
else
	revision=$(sed -n "s/^## ${caddy}-alpine-r\.\([^ ]*\) .*/\1/p" "${CHANGELOG}" | sed q)
	revision="$((${revision:-"-1"} + 1))"
fi
tag="${caddy}-alpine-r.${revision}"

updated=
TZ=UTC printf -v date '%(%Y-%m-%d)T' -1
entry="## ${tag} - ${date}\n"
if [[ ${#added[@]} -gt 0 ]]; then
	updated=true
	entry+="\n### Added\n\n"
	for module in "${added[@]}"; do
		entry+="- ${module} ${latest[${module}]}\n"
	done
fi
if [[ ${#changed[@]} -gt 0 ]]; then
	updated=true
	entry+="\n### Changed\n\n"
	for module in "${changed[@]}"; do
		entry+="- ${module} ${config[${module}]} to ${latest[${module}]}\n"
	done
fi
if [[ ${#removed[@]} -gt 0 ]]; then
	updated=true
	entry+="\n### Removed\n\n"
	for module in "${removed[@]}"; do
		entry+="- ${module} ${docker[${module}]}\n"
	done
fi

if [[ -n "${updated}" ]]; then
	printf '%b' "${entry}" >&2
else
	echo "Up to date." >&2
	[[ -z "${FORCE_RUN}" ]] && exit 0
	updated=true
fi

if [[ -n "${DRY_RUN}" ]]; then
	echo "Dry run. No changes will be made." >&2
	exit 0
fi

for module in "${!latest[@]}"; do
	sed -i "s|${module}@${config[${module}]}|${module}@${latest[${module}]}|g" "${MODULES_CONF}"
done

sep=
with_args=
for module in "${sorted[@]}"; do
	[[ "${module}" == "${CADDY_MODULE}" ]] && continue
	version="${latest[${module}]:-${config[${module}]}}"
	with_args+="${sep}--with ${module}@${version}"
	sep=$' \\\n'
done

cat >"${DOCKERFILE}" <<EOF
# Generated by update.sh — do not edit manually.
# Edit modules.conf and run this script again.

FROM caddy:${caddy}-builder-alpine AS builder

RUN --mount=type=cache,target=/go/pkg/mod \\
--mount=type=cache,target=/root/.cache/go-build \\
xcaddy build \\
${with_args}

FROM caddy:${caddy}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
EOF

printf '\n%b' "${entry}" >"${CHANGELOG}.tmp"
sed -i "/<!-- releases -->/r ${CHANGELOG}.tmp" "${CHANGELOG}"
rm "${CHANGELOG}.tmp"

[[ -z "${GITHUB_OUTPUT:-}" ]] && exit 0

{
	echo "tag=${tag}"
	echo "updated=${updated}"
} >>"${GITHUB_OUTPUT}"
